[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Gallery"
  pageRef = "galleries"
  weight = 30

[[main]]
  name = "Become"
  url = "https://howtobebetter.ai"
  weight = 40
